### PR TITLE
Bugfix: Styling issue due to Tailwind Preflight

### PR DESCRIPTION
**Pull request by JoJo-Bear**
Limited Tailwindcss to only exists within an id to prevent it to overrule styling of the developer

### CODE REVIEW

**Comment by supgeek-rod** [comment]
Greet job, but why review and merge are so slow?

**Comment by supgeek-rod** [comment]
@mckenziearts  Greet job ! 

When will this fix be release? Many users are waiting ...

**Comment by supgeek-rod** [comment]
Hi, @mckenziearts

When will the composer version be released?

**Comment by mckenziearts** [comment]
Hey @JoJo-Bear i removed complety sass to the project. the same issue with tailwind css appear. If you have time you can setup a fix. thank you

**Comment by JoJo-Bear** [comment]
Apologies @mckenziearts, I just read the response you gave. Is this still an issue? Or has it been solved in the meantime?

**Pull request merged**
